FROM eboraas/openai-gym

RUN pip install tflearn
RUN pip install tensorflow --upgrade
RUN pip install h5py
RUN apt-get update \
    && apt-get install -y \
        libav-tools \
        python-pyglet \
        python-opengl \
        libpq-dev \
        libjpeg-dev \
        libboost-all-dev \
        libsdl2-dev \
		xvfb\
		x11vnc\
	&& apt-get clean 

# Jupyter Notebook
EXPOSE 8888

# TensorBoard
EXPOSE 6006

# Xvnc
EXPOSE 5900

COPY "container-start.sh" "/opt/container-start.sh"
COPY "xsession-start.sh" "/opt/xsession-start.sh"
RUN chmod +x "/opt/container-start.sh" "/opt/xsession-start.sh"

WORKDIR /root

CMD ["/opt/container-start.sh"]
